// <auto-generated />
using BSES.DocumentManagementSystem.Encryption.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BSES.DocumentManagementSystem.Encryption.Data.Migrations
{
    [DbContext(typeof(DMSEncryptionDBContext))]
    partial class DMSEncryptionDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BSES.DocumentManagementSystem.Encryption.Data.DMSEncryptionKey", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EncryptionIV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyCode");

                    b.ToTable("DMSEncryptionKeys");

                    b.HasData(
                        new
                        {
                            CompanyCode = "BRPL",
                            EncryptionIV = "CaTOyz86Ad0TGyuWZts27A==",
                            EncryptionKey = "xyq2FaIYqbcwTuUlsiQ0UbJWAUCfh2JlmJVvwQs5Khg="
                        },
                        new
                        {
                            CompanyCode = "BYPL",
                            EncryptionIV = "G27D2ihSFZmREv17iBL0zQ==",
                            EncryptionKey = "QxZ5q8IuyjOn+Pyp3nucakA9jaieuKSvYZD8qLwYOqk="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
